PROJECT_NAME=space_invaders

INCLUDE_DIRECTORY=include
OBJECTS_DIRECTORY=objects
OUTPUT_DIRECTORY=output
SOURCES_DIRECTORY=sources

OUT_FILE=${OUTPUT_DIRECTORY}/${PROJECT_NAME}

CEXIL_DIRECTORY=../cexil
CEXIL_INCLUDE_DIRECTORY=${CEXIL_DIRECTORY}/include
CEXIL_OBJECT_FILE=${CEXIL_DIRECTORY}/library/cexil.o

CLIC3_DIRECTORY=../clic3
CLIC3_INCLUDE_DIRECTORY=${CLIC3_DIRECTORY}/include
CLIC3_OBJECT_FILE=${CLIC3_DIRECTORY}/library/clic3.o

INTERRUPT_HANDLER_DIRECTORY=../interrupt_handler
INTERRUPT_HANDLER_INCLUDE_DIRECTORY=${INTERRUPT_HANDLER_DIRECTORY}/include
INTERRUPT_HANDLER_OBJECT_FILE=${INTERRUPT_HANDLER_DIRECTORY}/library/interrupt_handler.o

SOURCE_FILES=${wildcard ${SOURCES_DIRECTORY}/*.c}
OBJECT_FILES=${patsubst ${SOURCES_DIRECTORY}/%.c, ${OBJECTS_DIRECTORY}/%.o, ${SOURCE_FILES}}

CC=gcc
C_FLAGS=-O3 -I${INCLUDE_DIRECTORY} -I${CEXIL_INCLUDE_DIRECTORY} -I${INTERRUPT_HANDLER_INCLUDE_DIRECTORY} -I${CLIC3_INCLUDE_DIRECTORY} -Wno-gnu-designator

${NAME}: ${OUT_FILE}

${OUT_FILE}: ${OBJECT_FILES} ${OUTPUT_DIRECTORY}
	${CC} ${C_FLAGS} ${OBJECT_FILES} ${CEXIL_OBJECT_FILE} ${CLIC3_OBJECT_FILE} ${INTERRUPT_HANDLER_OBJECT_FILE} -o $@

${OBJECTS_DIRECTORY}/%.o: ${SOURCES_DIRECTORY}/%.c ${OBJECTS_DIRECTORY}
	${CC} ${C_FLAGS} -c $< -o $@

${OUTPUT_DIRECTORY}:
	mkdir -p ${OUTPUT_DIRECTORY}

${OBJECTS_DIRECTORY}:
	mkdir -p ${OBJECTS_DIRECTORY}

clean:
	-rm ${OUT_FILE}
	-rm ${OBJECTS_DIRECTORY}/*.o 2> /dev/null

